# Site settings
title: Sonia Poltoratski, PhD
description: 

# Social media usernames (without @ symbol)
github_username: soniapolt
twitter_username: soniapolt
linkedin_username: soniapolt
google_scholar_id: vnrWoQwAAAAJ
email: soniapolt@gmail.com

# Profile photo path
avatar: /assets/images/headshot_sf.png

# Theme settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Styling
css:
  - /assets/css/custom.css

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme